
name: Build and Publish Docker Image

on:
  push:
    branches:
      - master  # Puedes cambiar esta rama si es necesario

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t tu_usuario/flask-docker:${{ github.sha }} .
        docker tag tu_usuario/flask-docker:${{ github.sha }} tu_usuario/flask-docker:latest

    - name: Push Docker image
      run: |
        docker push tu_usuario/flask-docker:${{ github.sha }}
        docker push tu_usuario/flask-docker:latest
